/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('attributesOfCities').del()
  await knex('attributesOfCities').insert([
    { city_id: '1', attribute_id: '1' },
    { city_id: '1', attribute_id: '3' },
    { city_id: '1', attribute_id: '4' },
    { city_id: '1', attribute_id: '9' },
    { city_id: '1', attribute_id: '10' },
    { city_id: '2', attribute_id: '3' },
    { city_id: '2', attribute_id: '4' },
    { city_id: '2', attribute_id: '6' },
    { city_id: '2', attribute_id: '9' },
    { city_id: '2', attribute_id: '10' },
    { city_id: '3', attribute_id: '1' },
    { city_id: '3', attribute_id: '3' },
    { city_id: '3', attribute_id: '6' },
    { city_id: '3', attribute_id: '10' },
    { city_id: '3', attribute_id: '11' },
    { city_id: '4', attribute_id: '1' },
    { city_id: '4', attribute_id: '4' },
    { city_id: '4', attribute_id: '6' },
    { city_id: '4', attribute_id: '9' },
    { city_id: '4', attribute_id: '11' },
    { city_id: '5', attribute_id: '3' },
    { city_id: '5', attribute_id: '5' },
    { city_id: '5', attribute_id: '6' },
    { city_id: '5', attribute_id: '7' },
    { city_id: '5', attribute_id: '12' },
    { city_id: '6', attribute_id: '1' },
    { city_id: '6', attribute_id: '5' },
    { city_id: '6', attribute_id: '7' },
    { city_id: '6', attribute_id: '9' },
    { city_id: '6', attribute_id: '10' },
    { city_id: '7', attribute_id: '1' },
    { city_id: '7', attribute_id: '2' },
    { city_id: '7', attribute_id: '4' },
    { city_id: '7', attribute_id: '9' },
    { city_id: '7', attribute_id: '10' },
    { city_id: '8', attribute_id: '1' },
    { city_id: '8', attribute_id: '2' },
    { city_id: '8', attribute_id: '4' },
    { city_id: '8', attribute_id: '9' },
    { city_id: '8', attribute_id: '11' },
    { city_id: '9', attribute_id: '5' },
    { city_id: '9', attribute_id: '6' },
    { city_id: '9', attribute_id: '7' },
    { city_id: '9', attribute_id: '8' },
    { city_id: '9', attribute_id: '12' },
    { city_id: '10', attribute_id: '1' },
    { city_id: '10', attribute_id: '4' },
    { city_id: '10', attribute_id: '6' },
    { city_id: '10', attribute_id: '8' },
    { city_id: '10', attribute_id: '9' },
    { city_id: '11', attribute_id: '1' },
    { city_id: '11', attribute_id: '3' },
    { city_id: '11', attribute_id: '4' },
    { city_id: '11', attribute_id: '6' },
    { city_id: '11', attribute_id: '9' },
    { city_id: '12', attribute_id: '3' },
    { city_id: '12', attribute_id: '4' },
    { city_id: '12', attribute_id: '6' },
    { city_id: '12', attribute_id: '9' },
    { city_id: '12', attribute_id: '11' },
    { city_id: '13', attribute_id: '2' },
    { city_id: '13', attribute_id: '3' },
    { city_id: '13', attribute_id: '5' },
    { city_id: '13', attribute_id: '7' },
    { city_id: '13', attribute_id: '9' },
  ])
}
